import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "docs" / "openapi.json"
OUTPUT_PATH = ROOT / "src" / "api" / "generated" / "types.ts"


def schema_to_ts(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]

    if "anyOf" in schema:
        return union_to_ts(schema["anyOf"])
    if "oneOf" in schema:
        return union_to_ts(schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(schema_to_ts(item) for item in schema["allOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return union_to_ts([{"type": item} for item in schema_type])

    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = schema_to_ts(schema.get("items", {}))
        return f"{item_type}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if additional:
            value_type = schema_to_ts(additional if isinstance(additional, dict) else {})
            return f"Record<string, {value_type}>"
        if "properties" in schema:
            return object_to_ts(schema)
        return "Record<string, unknown>"

    return "unknown"


def union_to_ts(items):
    parts = []
    for item in items:
        part = schema_to_ts(item)
        if part not in parts:
            parts.append(part)
    return " | ".join(parts) if parts else "unknown"


def object_to_ts(schema):
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    if not properties:
        return "Record<string, unknown>"

    lines = ["{"]
    for name, property_schema in properties.items():
        optional = "" if name in required else "?"
        lines.append(f"  {json.dumps(name)}{optional}: {schema_to_ts(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def type_name(name):
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if re.match(r"^[0-9]", normalized):
        normalized = f"Schema_{normalized}"
    return normalized


def main():
    openapi = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    schemas = openapi.get("components", {}).get("schemas", {})

    lines = [
        "// AUTO-GENERATED by scripts/export_ts_types.py",
        "// Do not edit by hand. Update docs/openapi.json, then regenerate.",
        "",
    ]

    exported_names = []
    for raw_name in sorted(schemas):
        name = type_name(raw_name)
        exported_names.append(name)
        ts_type = schema_to_ts(schemas[raw_name])
        lines.append(f"export type {name} = {ts_type};")
        lines.append("")

    lines.append("export type ApiSchemas = {")
    for name in exported_names:
        lines.append(f"  {json.dumps(name)}: {name};")
    lines.append("};")
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"TypeScript types exported to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
